# Generated by Django 5.2.9 on 2025-12-31 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کالا/خدمت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (AC)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/', verbose_name='تصویر محصول')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='موجودی انبار')),
                ('is_active', models.BooleanField(default=True, verbose_name='قابل نمایش')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تحویل'), ('DELIVERED', 'تحویل داده شد'), ('CANCELED', 'لغو شده')], default='PENDING', max_length=10, verbose_name='وضعیت تحویل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='خریدار')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shopitem', verbose_name='کالا')),
            ],
        ),
    ]
