# Generated by Django 5.2.9 on 2025-12-31 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='stock',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='category',
            field=models.CharField(choices=[('گجت', 'گجت و ابزار'), ('روزانه', 'مصارف روزانه')], default='گجت', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shopitem'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار تحویل'), ('DELIVERED', 'تحویل داده شد'), ('CANCELED', 'لغو شده')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
