# Generated by Django 5.2.9 on 2025-12-31 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ماموریت')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('reward_amount', models.PositiveIntegerField(verbose_name='پاداش (AC)')),
                ('deadline', models.DateTimeField(verbose_name='مهلت انجام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('check_in', models.TimeField(auto_now_add=True, verbose_name='ساعت ورود')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='ساعت خروج')),
                ('delay_minutes', models.PositiveIntegerField(default=0, verbose_name='دقایق تاخیر')),
                ('is_penalty_applied', models.BooleanField(default=False, verbose_name='جریمه اعمال شده؟')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
        ),
        migrations.CreateModel(
            name='MissionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_link', models.URLField(blank=True, null=True, verbose_name='لینک مستندات (Drive/Notion)')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='missions/', verbose_name='تصویر ضمیمه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات کارمند')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=10, verbose_name='وضعیت')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('admin_feedback', models.TextField(blank=True, verbose_name='بازخورد مدیر')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.mission', verbose_name='ماموریت مربوطه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='موضوع آموزش')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='مدت زمان (دقیقه)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید نهایی ادمین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
        ),
    ]
