# Generated by Django 5.2.9 on 2026-01-01 06:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='reward_amount',
            new_name='reward_ac',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_penalty_applied',
        ),
        migrations.RemoveField(
            model_name='missionsubmission',
            name='proof_image',
        ),
        migrations.RemoveField(
            model_name='missionsubmission',
            name='proof_link',
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='daily_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='On-time', max_length=20),
        ),
        migrations.AddField(
            model_name='mission',
            name='category',
            field=models.CharField(choices=[('performance', 'عملکردی (KPI)'), ('cultural', 'فرهنگی'), ('discipline', 'نظمی'), ('creative', 'خلاقیت')], default='performance', max_length=50),
        ),
        migrations.AddField(
            model_name='missionsubmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='missionsubmission',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='delay_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mission',
            name='deadline',
            field=models.CharField(blank=True, help_text='تاریخ شمسی مثل ۱۴۰۳/۱۰/۲۰', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='missionsubmission',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missionsubmission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='missionsubmission',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.mission'),
        ),
        migrations.AlterField(
            model_name='missionsubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='missionsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='missionsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='topic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
