# Generated by Django 5.2.9 on 2025-12-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نشان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('icon_name', models.CharField(max_length=50, verbose_name='نام آیکون (Lucide)')),
                ('criteria', models.TextField(verbose_name='شرط دریافت')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مقدار (AC)')),
                ('token_type', models.CharField(choices=[('PERFORMANCE', 'توکن عملکرد'), ('DISCIPLINE', 'توکن نظم'), ('CULTURAL', 'توکن فرهنگی'), ('IDEA', 'توکن ایده ترند'), ('PURCHASE', 'خرید از فروشگاه'), ('ADMIN', 'اصلاح مدیریتی')], max_length=20, verbose_name='نوع توکن')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ دریافت')),
            ],
        ),
    ]
