# Generated by Django 5.2.9 on 2026-01-01 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('gadget', 'گجت و ابزار'), ('daily', 'مصارف روزانه'), ('digital', 'دیجیتال'), ('service', 'خدمات و مرخصی')], default='gadget', max_length=50)),
                ('stock', models.IntegerField(default=-1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StakingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration_months', models.PositiveIntegerField(help_text='مدت زمان به ماه')),
                ('profit_percent', models.PositiveIntegerField(help_text='درصد سود')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='badge',
            name='criteria',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token_type',
            field=models.CharField(choices=[('PERFORMANCE', 'عملکرد'), ('DISCIPLINE', 'نظم'), ('CULTURAL', 'فرهنگی'), ('IDEA', 'ایده و خلاقیت'), ('SPEND', 'خرید/خرج'), ('STAKING', 'سرمایه\u200cگذاری'), ('ADMIN', 'اصلاح مدیریتی')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='earned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
